### ISSUE TITLE
Link to "modele de declaratii" not loading

### ISSUE THREAD

**Issue by danmana** [code4romania/stiri-oficiale#84]
In the "Instrumente Utile" section, the link for "Modele de declaratii" loads:

https://cetrebuiesafac.ro/adaptare-si-rezistenta/modele-de-declaratii

Which is rendered as an empty page with error:
```
2.0b7f7379.chunk.js:2 Uncaught TypeError: Cannot read property 'slug' of undefined
    at main.c5599862.chunk.js:1
    at Array.filter (<anonymous>)
    at main.c5599862.chunk.js:1
    at h (main.c5599862.chunk.js:1)
    at Wo (2.0b7f7379.chunk.js:2)
    at vl (2.0b7f7379.chunk.js:2)
    at cu (2.0b7f7379.chunk.js:2)
    at lu (2.0b7f7379.chunk.js:2)
    at $l (2.0b7f7379.chunk.js:2)
    at 2.0b7f7379.chunk.js:2
```

**Comment by andreiio** [comment]
It seems to load just fine here.

![cetrebuiesafac ro_adaptare-si-rezistenta_modele-de-declaratii](https://user-images.githubusercontent.com/1569300/79880574-1e2ae380-83e8-11ea-9d37-709764fc4615.png)

If there's an issue how that page is rendered, please report it on [code4romania/ce-ma-fac](https://github.com/code4romania/ce-ma-fac)
