### ISSUE TITLE
RSS endpoint lipsă

### ISSUE THREAD

**Issue by florinj** [code4romania/stiri-oficiale#96]
Salut 
Aș dori să întreb dacă se poate adăuga un feed. 
Ar ajuta la preluarea automată de date și ar reduce încărcarea serverelor, păstrând totuși referința.
Diseminarea datelor ar fi mult mai largă.
Mulțumesc.
F.J.

**Comment by andreiio** [comment]
Salut,

stirioficiale.ro are feed-uri RSS din săptămâna lansării (#43). Îmi poți spune mai exact ce lipsește?

**Comment by andreiio** [comment]
Am mutat aici comentariile din pull request, ca să fie mai ușor de urmărit

> @florinj 
> Salut
> Am încercat diferite adrese cu .../rss, .../feed, .../atom etc. și nu merge.
> Dacă este rss implementat eu nu am găsit link-ul care să reîntoarcă un feed.
> Ar trebui să fie unul pus în footer sau header sau în sidebar.
> Mai caut ...
> Dar dacă spui că este așa, aprecia foarte mult să-mi spui unde găsesc acel link pe site-ul stirioficiale.ro .
> Dar oricum și așa este aici o problemă, dacă n-am putut să găsesc ușor acel link, chiar dacă funcționalitatea există.
> Toate cele bune,
> F.J.
  
>@florinj
> M-am uitat în sursă și am găsit link-urile.
> Mai rămâne problema afișării la vedere a unui link în pagină.

Link-urile pe care le-ai găsit în sursă permit clienților RSS să descopere automat feed-urile disponibile. Acest feature se numește RSS Autodiscovery, [există din 2006](https://www.rssboard.org/rss-autodiscovery) și funcționează astfel:

![Screen Recording](https://user-images.githubusercontent.com/1569300/87077065-7b317b00-c21a-11ea-9e6f-4c33a2b7499d.gif)

Din punctul meu de vedere feature-ul e funcțional și fără link-uri vizibile în pagină.

**Comment by florinj** [comment]
OK. Mulțumesc pentru răspuns.
